[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About us"
  pageRef = "about"
  weight = 20

[[main]]
  name = "History"
  pageRef = "history"
  weight = 30



[[footer]]
  name = "Facebook"
  url = "https://facebook.com"


[[footer]]
  name = "Discord"
  url = "https://discord.gg/M4AgESXB"
