[[main]]
pageRef = "/"
weight = 10

[[footer]]
name = "{{< icon facebook >}} Facebook"
url = "https://www.facebook.com/szegedkungfu"

[[footer]]
name = "{{< icon discord >}} Discord"
url = "https://discord.gg/M4AgESXB"
