[[main]]
pageRef = "/"
weight = 10

# [[footer]]
# name = "{{< icon facebook >}} Facebook"
# url = "https://facebook.com"


[[footer]]
name = "{{< icon discord >}} Discord"
url = "https://discord.gg/M4AgESXB"
